version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: ecommerce_analytics_app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: ecommerce_analytics_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
