"""
Cohort Retention & Customer Lifecycle Analysis.
Calculates acquisition cohort retention matrices, revenue retention heatmaps,
and geographic/purchase frequency retention slices.
"""

from typing import Dict, Tuple
import numpy as np
import pandas as pd


def compute_cohort_metrics(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Computes cohort retention and revenue matrices.
    
    Returns:
        cohort_counts: Customer count retention matrix.
        retention_matrix: Percentage retention matrix (Cohort Month vs Period Index).
        revenue_matrix: Revenue generated by each cohort over time.
    """
    data = df.copy()

    # 1. Invoice month and Customer cohort month
    data["InvoiceMonth"] = data["InvoiceDate"].dt.to_period("M")
    data["CohortMonth"] = (
        data.groupby("CustomerID")["InvoiceDate"]
        .transform("min")
        .dt.to_period("M")
    )

    # 2. Cohort Index (0, 1, 2, ... months passed)
    def get_cohort_index(df_in):
        year_diff = df_in["InvoiceMonth"].dt.year - df_in["CohortMonth"].dt.year
        month_diff = df_in["InvoiceMonth"].dt.month - df_in["CohortMonth"].dt.month
        return year_diff * 12 + month_diff

    data["CohortIndex"] = get_cohort_index(data)

    # 3. Group by CohortMonth and CohortIndex
    cohort_group = data.groupby(["CohortMonth", "CohortIndex"])

    # Count unique active customers
    cohort_counts = (
        cohort_group["CustomerID"]
        .nunique()
        .reset_index()
        .pivot(index="CohortMonth", columns="CohortIndex", values="CustomerID")
    )

    # Calculate retention percentage relative to cohort size (Month 0)
    cohort_sizes = cohort_counts.iloc[:, 0]
    retention_matrix = cohort_counts.divide(cohort_sizes, axis=0) * 100
    retention_matrix = np.round(retention_matrix, 2)

    # Revenue matrix
    revenue_matrix = (
        cohort_group["TotalAmount"]
        .sum()
        .reset_index()
        .pivot(index="CohortMonth", columns="CohortIndex", values="TotalAmount")
        .fillna(0)
    )
    revenue_matrix = np.round(revenue_matrix, 2)

    return cohort_counts, retention_matrix, revenue_matrix


def compute_geographic_cohort_retention(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes average month-1 and month-3 retention by geographic market.
    """
    data = df.copy()
    data["InvoiceMonth"] = data["InvoiceDate"].dt.to_period("M")
    data["CohortMonth"] = (
        data.groupby("CustomerID")["InvoiceDate"]
        .transform("min")
        .dt.to_period("M")
    )

    year_diff = data["InvoiceMonth"].dt.year - data["CohortMonth"].dt.year
    month_diff = data["InvoiceMonth"].dt.month - data["CohortMonth"].dt.month
    data["CohortIndex"] = year_diff * 12 + month_diff

    geo_summary = []
    # Major markets
    top_countries = data["Country"].value_counts().head(8).index.tolist()

    for country in top_countries:
        sub = data[data["Country"] == country]
        pivot = (
            sub.groupby(["CohortMonth", "CohortIndex"])["CustomerID"]
            .nunique()
            .reset_index()
            .pivot(index="CohortMonth", columns="CohortIndex", values="CustomerID")
        )
        if 0 in pivot.columns and len(pivot) > 0:
            m0 = pivot[0].sum()
            m1 = pivot[1].sum() if 1 in pivot.columns else 0
            m3 = pivot[3].sum() if 3 in pivot.columns else 0
            m1_rate = round((m1 / m0) * 100, 2) if m0 > 0 else 0.0
            m3_rate = round((m3 / m0) * 100, 2) if m0 > 0 else 0.0
            total_rev = round(sub["TotalAmount"].sum(), 2)
            geo_summary.append({
                "Country": country,
                "TotalCustomers": int(sub["CustomerID"].nunique()),
                "TotalRevenue": total_rev,
                "Month_1_Retention_Pct": m1_rate,
                "Month_3_Retention_Pct": m3_rate,
            })

    geo_df = pd.DataFrame(geo_summary)
    return geo_df.sort_values(by="TotalRevenue", ascending=False).reset_index(drop=True)


if __name__ == "__main__":
    from src.data_loader import load_raw_data
    from src.cleaner import clean_retail_data

    raw = load_raw_data()
    clean, _ = clean_retail_data(raw)
    counts, retention, rev = compute_cohort_metrics(clean)
    geo_ret = compute_geographic_cohort_retention(clean)

    print("=== Customer Retention Rate Matrix (%) ===")
    print(retention.to_string())
    print("\n=== Geographic Retention Summary ===")
    print(geo_ret.to_string(index=False))
